spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/auth
#      uri: ${MONGO_URI:mongodb://localhost:27017/auth} //todo for docker
logging:
  level:
    root: INFO
    com.automorfosi.mathisi: INFO
  file:
    name: authentication_api.log